version: '2.1'
services:
    artemis-mysql:
        extends:
            file: mysql.yml
            service: artemis-mysql

    artemis-app:
        image: ghcr.io/ls1intum/artemis
        build:
            context: ../../../..
            dockerfile: src/main/docker/Dockerfile
        volumes:
            - ../../resources/config/application-dev.yml:/home/artemis/application-dev.yml:ro
            - ../../resources/config/application-artemis.yml:/home/artemis/application-artemis.yml:ro
        environment:
            _JAVA_OPTIONS: "-Xmx5120m -Xms2560m"
            JHIPSTER_SLEEP: 30 # gives time for other services to boot before the application
            spring.profiles.active: "dev,bamboo,bitbucket,jira,artemis,scheduling,athene"
            spring.datasource.url: "${DATASOURCE_URL}"
            spring.datasource.username: root
            spring.datasource.password: ""
            artemis.user-management.external.url: "${UM_URL}"
            artemis.user-management.external.user: "${UM_USER}"
            artemis.user-management.external.password: "${UM_PASSWORD}"
            artemis.version-control.url: "${SCM_URL}"
            artemis.version-control.user: "${SCM_USER}"
            artemis.version-control.password: "${SCM_PASSWORD}"
            artemis.continuous-integration.url: "${CI_URL}"
            artemis.continuous-integration.user: "${CI_USER}"
            artemis.continuous-integration.password: "${CI_PASSWORD}"
        ports:
            - 8080:8080
        networks:
            - artemis
        depends_on:
            artemis-mysql:
                condition: service_healthy

    artemis-cypress:
        image: cypress/browsers:node16.5.0-chrome94-ff93
        depends_on:
            - artemis-app
            - artemis-mysql
        environment:
            - CYPRESS_baseUrl
            - CYPRESS_adminUsername
            - CYPRESS_adminPassword
            - CYPRESS_username
            - CYPRESS_password
            - CYPRESS_allowGroupCustomization
            - CYPRESS_studentGroupName
            - CYPRESS_tutorGroupName
            - CYPRESS_editorGroupName
            - CYPRESS_instructorGroupName
        # Give Artemis 120 seconds to start
        command: sh -c "sleep 120 && cd /app/artemis/src/test/cypress && chmod 777 /root && npm ci &&npm run cypress:run"
        volumes:
            - ../../../../:/app/artemis
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
