version: '2.1'
services:
    artemis-mysql:
        extends:
            file: mysql.yml
            service: artemis-mysql

    artemis-app:
        image: ghcr.io/ls1intum/artemis
        build:
            context: ../../../..
            dockerfile: src/main/docker/Dockerfile
        volumes:
            - ../../resources/config/application-dev.yml:/home/artemis/application-dev.yml:ro
            - ../../resources/config/application-artemis.yml:/home/artemis/application-artemis.yml:ro
        environment:
            - JAVA_OPTIONS
            - SPRING_DATASOURCE_URL
            - SPRING_DATASOURCE_USERNAME
            - SPRING_DATASOURCE_PASSWORD
            - SPRING_PROFILES_ACTIVE
            - JHIPSTER_SLEEP
            - ARTEMIS_USERMANAGEMENT_EXTERNAL_URL
            - ARTEMIS_USERMANAGEMENT_EXTERNAL_USER
            - ARTEMIS_USERMANAGEMENT_EXTERNAL_PASSWORD
            - ARTEMIS_VERSIONCONTROL_URL
            - ARTEMIS_VERSIONCONTROL_USER
            - ARTEMIS_VERSIONCONTROL_PASSWORD
            - ARTEMIS_CONTINUOUSINTEGRATION_URL
            - ARTEMIS_CONTINUOUSINTEGRATION_USER
            - ARTEMIS_CONTINUOUSINTEGRATION_PASSWORD
        ports:
            - 8080:8080
        networks:
            - artemis
        depends_on:
            artemis-mysql:
                condition: service_healthy

    artemis-cypress:
        image: cypress/browsers:node16.5.0-chrome94-ff93
        depends_on:
            - artemis-app
            - artemis-mysql
        environment:
            - CYPRESS_baseUrl
            - CYPRESS_adminUsername
            - CYPRESS_adminPassword
            - CYPRESS_username
            - CYPRESS_password
            - CYPRESS_allowGroupCustomization
            - CYPRESS_studentGroupName
            - CYPRESS_tutorGroupName
            - CYPRESS_editorGroupName
            - CYPRESS_instructorGroupName
        # Give Artemis 120 seconds to start
        command: sh -c "sleep 120 && cd /app/artemis/src/test/cypress && chmod 777 /root && npm ci &&npm run cypress:run"
        volumes:
            - ../../../../:/app/artemis
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
